#!/bin/bash
# ═══════════════════════════════════════════════════════════
# ONE-CLICK FACTORY SETUP
#
# Reads factory.conf and sets up the entire AI Software Factory
# on your chosen target (local rack, AWS, Azure, GCP, etc.)
#
# Usage:
#   1. Edit factory.conf with your settings
#   2. bash setup.sh
# ═══════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FILE="$SCRIPT_DIR/factory.conf"

# ── Load config ────────────────────────────────────────────
if [ ! -f "$CONF_FILE" ]; then
    echo "ERROR: factory.conf not found at $CONF_FILE"
    echo "Copy factory.conf.example to factory.conf and edit it."
    exit 1
fi

# Source config (skip comments and empty lines)
set -a
source <(grep -v '^\s*#' "$CONF_FILE" | grep -v '^\s*$')
set +a

echo "══════════════════════════════════════════════════════"
echo "  Autonomous AI Software Factory — One-Click Setup"
echo "  Target: $FACTORY_TARGET"
echo "══════════════════════════════════════════════════════"

# ── Run system validation ──────────────────────────────────
echo ""
echo "Running system validation..."
echo ""
VALIDATE_SCRIPT="$SCRIPT_DIR/validate.sh"
if [ -f "$VALIDATE_SCRIPT" ]; then
    chmod +x "$VALIDATE_SCRIPT"
    bash "$VALIDATE_SCRIPT" "$FACTORY_TARGET"
    VALIDATE_EXIT=$?
    if [ "$VALIDATE_EXIT" -eq 1 ]; then
        echo ""
        echo "ERROR: System validation failed. Fix the errors above and re-run."
        exit 1
    elif [ "$VALIDATE_EXIT" -eq 2 ]; then
        echo ""
        read -p "Warnings found. Continue anyway? (y/N): " CONTINUE
        if [ "${CONTINUE,,}" != "y" ]; then
            echo "Aborted."
            exit 1
        fi
    fi
    echo ""
fi

# ── Generate secrets ───────────────────────────────────────
GATEWAY_TOKEN=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 16)

generate_env_file() {
    local ENV_DIR="$1"
    cat > "$ENV_DIR/.env" << ENVEOF
# Auto-generated by setup.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY
GOOGLE_AI_API_KEY=$GOOGLE_AI_API_KEY
DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY
META_API_KEY=$META_API_KEY
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_CEO_CHAT_ID=$TELEGRAM_CEO_CHAT_ID
WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID:-}
WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN:-}
WHATSAPP_CEO_PHONE=${WHATSAPP_CEO_PHONE:-}
GITHUB_TOKEN=$GITHUB_TOKEN
DOCKER_HOST=unix:///var/run/docker.sock
VALKEY_URL=redis://factory-valkey:6379
GATEWAY_TOKEN=$GATEWAY_TOKEN
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
OLLAMA_HOST=http://factory-ollama:11434
OLLAMA_API_KEY=ollama-local
FACTORY_DOMAIN=${CLOUD_DOMAIN:-localhost}
PHASE_BUDGET_LIMIT=$PHASE_BUDGET_LIMIT
TOTAL_BUDGET_LIMIT=$TOTAL_BUDGET_LIMIT
ENVEOF
    echo "  .env generated at $ENV_DIR/.env"
}

# ── Install base dependencies (local machine) ─────────────
install_base_local() {
    echo "[1/4] Checking prerequisites..."

    # Docker
    if ! command -v docker &> /dev/null; then
        echo "  Installing Docker..."
        curl -fsSL https://get.docker.com | sh
        sudo systemctl enable docker && sudo systemctl start docker
    else
        echo "  Docker: $(docker --version)"
    fi

    # Docker Compose
    docker compose version > /dev/null 2>&1 || {
        echo "ERROR: Docker Compose V2 not found. Update Docker."
        exit 1
    }

    # Node.js
    if ! command -v node &> /dev/null || [[ $(node --version | cut -d. -f1 | tr -d v) -lt 24 ]]; then
        echo "  Installing Node.js 24..."
        if command -v brew &> /dev/null; then
            brew install node@24
        elif [ -f /etc/debian_version ]; then
            curl -fsSL https://deb.nodesource.com/setup_24.x | sudo bash -
            sudo apt-get install -y nodejs
        else
            echo "  Please install Node.js 24 manually."
            exit 1
        fi
    else
        echo "  Node.js: $(node --version)"
    fi

    # OpenClaw
    if ! command -v openclaw &> /dev/null; then
        echo "  Installing OpenClaw..."
        npm install -g openclaw
    else
        echo "  OpenClaw: $(openclaw --version 2>/dev/null || echo 'installed')"
    fi
}

# ── NVIDIA GPU setup (local rack only) ────────────────────
setup_gpu() {
    if [ "${HAS_GPU:-false}" = "true" ]; then
        echo "[2/4] Setting up GPU..."
        if command -v nvidia-smi &> /dev/null; then
            echo "  GPU detected: $(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)"
            # Install NVIDIA Container Toolkit if missing
            if ! dpkg -l nvidia-container-toolkit &> /dev/null 2>&1; then
                echo "  Installing NVIDIA Container Toolkit..."
                curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | \
                    sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
                curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
                    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
                    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
                sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
                sudo nvidia-ctk runtime configure --runtime=docker
                sudo systemctl restart docker
            fi
            echo "  NVIDIA Container Toolkit: ready"
        else
            echo "  WARNING: HAS_GPU=true but nvidia-smi not found."
            echo "  Install NVIDIA drivers first: sudo apt install nvidia-driver-550"
            echo "  Continuing without GPU (Ollama will use CPU, which is slow)..."
        fi
    else
        echo "[2/4] No GPU configured, skipping Ollama GPU setup."
    fi
}

# ═══════════════════════════════════════════════════════════
# TARGET: LOCAL RACK
# ═══════════════════════════════════════════════════════════
setup_local() {
    echo ""
    echo "Setting up factory on LOCAL RACK..."
    echo ""

    install_base_local
    setup_gpu

    echo "[3/4] Generating .env..."
    generate_env_file "$SCRIPT_DIR"

    echo "[4/4] Starting factory..."
    cd "$SCRIPT_DIR"
    docker compose -f infrastructure/docker-compose.local-rack.yml up -d

    # Pull local models if GPU is available
    if [ "${HAS_GPU:-false}" = "true" ]; then
        echo ""
        echo "Pulling local LLM models (this may take 10-30 minutes)..."
        sleep 10  # Wait for Ollama container to start
        docker exec factory-ollama ollama pull qwen2.5-coder:32b || echo "  Model pull failed — retry manually: docker exec factory-ollama ollama pull qwen2.5-coder:32b"
        docker exec factory-ollama ollama pull gemma3:27b || echo "  Model pull failed — retry manually"
    fi

    echo ""
    echo "══════════════════════════════════════════════════"
    echo "  LOCAL RACK SETUP COMPLETE"
    echo ""
    echo "  Factory Portal:  http://localhost:18789"
    echo "  Coolify (deploy): http://localhost:8000"
    echo "  Dockge:           http://localhost:5001"
    echo "  Ollama:           http://localhost:11434"
    echo "  PostgreSQL:       localhost:5432"
    echo "  Redis:            localhost:6379"
    echo ""
    echo "  Send your first idea to Telegram and watch it build."
    echo "══════════════════════════════════════════════════"
}

# ═══════════════════════════════════════════════════════════
# TARGET: CLOUD (provisions VM, copies files, starts factory)
# ═══════════════════════════════════════════════════════════

provision_cloud_vm() {
    local PROVIDER="$1"
    echo "[1/5] Provisioning $PROVIDER VM..."

    case "$PROVIDER" in
        aws)
            echo "  Creating AWS EC2 instance..."
            # Create security group
            aws ec2 create-security-group \
                --group-name "$AWS_SECURITY_GROUP" \
                --description "Factory security group" \
                --region "$AWS_REGION" 2>/dev/null || true
            # Open ports: SSH, HTTP, HTTPS
            for PORT in 22 80 443; do
                aws ec2 authorize-security-group-ingress \
                    --group-name "$AWS_SECURITY_GROUP" \
                    --protocol tcp --port "$PORT" --cidr 0.0.0.0/0 \
                    --region "$AWS_REGION" 2>/dev/null || true
            done
            # Launch instance
            INSTANCE_ID=$(aws ec2 run-instances \
                --image-id "$AWS_AMI" \
                --instance-type "$AWS_INSTANCE_TYPE" \
                --key-name "$AWS_KEY_PAIR_NAME" \
                --security-groups "$AWS_SECURITY_GROUP" \
                --block-device-mappings "[{\"DeviceName\":\"/dev/sda1\",\"Ebs\":{\"VolumeSize\":$AWS_VOLUME_SIZE}}]" \
                --region "$AWS_REGION" \
                --query 'Instances[0].InstanceId' --output text)
            echo "  Instance: $INSTANCE_ID"
            echo "  Waiting for public IP..."
            aws ec2 wait instance-running --instance-ids "$INSTANCE_ID" --region "$AWS_REGION"
            SERVER_IP=$(aws ec2 describe-instances \
                --instance-ids "$INSTANCE_ID" --region "$AWS_REGION" \
                --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
            SERVER_USER="ubuntu"
            echo "  IP: $SERVER_IP"
            ;;

        azure)
            echo "  Creating Azure VM..."
            az group create --name "$AZURE_RESOURCE_GROUP" --location "$AZURE_REGION"
            az vm create \
                --resource-group "$AZURE_RESOURCE_GROUP" \
                --name factory-vm \
                --image "$AZURE_IMAGE" \
                --size "$AZURE_VM_SIZE" \
                --admin-username azureuser \
                --ssh-key-values "$SSH_KEY_PATH.pub" \
                --public-ip-sku Standard \
                --os-disk-size-gb 100
            SERVER_IP=$(az vm show -d -g "$AZURE_RESOURCE_GROUP" -n factory-vm \
                --query publicIps -o tsv)
            SERVER_USER="azureuser"
            # Open ports
            az vm open-port --port 80,443 -g "$AZURE_RESOURCE_GROUP" -n factory-vm
            echo "  IP: $SERVER_IP"
            ;;

        gcp)
            echo "  Creating GCP VM..."
            gcloud compute instances create factory-vm \
                --project="$GCP_PROJECT" \
                --zone="$GCP_ZONE" \
                --machine-type="$GCP_MACHINE_TYPE" \
                --image-family="$GCP_IMAGE_FAMILY" \
                --image-project="$GCP_IMAGE_PROJECT" \
                --boot-disk-size="${GCP_DISK_SIZE}GB" \
                --tags=factory-server
            # Firewall rules
            gcloud compute firewall-rules create factory-allow-web \
                --allow tcp:80,tcp:443 --target-tags=factory-server \
                --project="$GCP_PROJECT" 2>/dev/null || true
            SERVER_IP=$(gcloud compute instances describe factory-vm \
                --zone="$GCP_ZONE" --project="$GCP_PROJECT" \
                --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
            SERVER_USER="$(whoami)"
            echo "  IP: $SERVER_IP"
            ;;

        hetzner)
            echo "  Creating Hetzner server..."
            RESPONSE=$(curl -s -X POST "https://api.hetzner.cloud/v1/servers" \
                -H "Authorization: Bearer $HETZNER_API_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{
                    \"name\": \"factory\",
                    \"server_type\": \"$HETZNER_SERVER_TYPE\",
                    \"image\": \"ubuntu-24.04\",
                    \"location\": \"$HETZNER_LOCATION\",
                    \"ssh_keys\": []
                }")
            SERVER_IP=$(echo "$RESPONSE" | jq -r '.server.public_net.ipv4.ip')
            SERVER_USER="root"
            echo "  IP: $SERVER_IP"
            echo "  Root password in Hetzner console (or use SSH keys)."
            ;;

        digitalocean)
            echo "  Creating DigitalOcean droplet..."
            RESPONSE=$(curl -s -X POST "https://api.digitalocean.com/v2/droplets" \
                -H "Authorization: Bearer $DO_API_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{
                    \"name\": \"factory\",
                    \"region\": \"$DO_REGION\",
                    \"size\": \"$DO_SIZE\",
                    \"image\": \"ubuntu-24-04-x64\"
                }")
            DROPLET_ID=$(echo "$RESPONSE" | jq -r '.droplet.id')
            echo "  Waiting for IP..."
            sleep 30
            SERVER_IP=$(curl -s "https://api.digitalocean.com/v2/droplets/$DROPLET_ID" \
                -H "Authorization: Bearer $DO_API_TOKEN" | \
                jq -r '.droplet.networks.v4[] | select(.type=="public") | .ip_address')
            SERVER_USER="root"
            echo "  IP: $SERVER_IP"
            ;;

        *)
            echo "ERROR: Unknown provider: $PROVIDER"
            exit 1
            ;;
    esac

    echo "  Server provisioned at $SERVER_IP"
    export SERVER_IP SERVER_USER
}

setup_remote_server() {
    echo "[2/5] Waiting for SSH to be available..."
    for i in $(seq 1 30); do
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 \
            -i "$SSH_KEY_PATH" "$SERVER_USER@$SERVER_IP" "echo ok" 2>/dev/null && break
        echo "  Attempt $i/30..."
        sleep 10
    done

    echo "[3/5] Installing dependencies on remote server..."
    ssh -i "$SSH_KEY_PATH" "$SERVER_USER@$SERVER_IP" << 'REMOTE_SETUP'
        set -euo pipefail
        export DEBIAN_FRONTEND=noninteractive

        # Update
        apt-get update && apt-get upgrade -y
        apt-get install -y curl git wget jq

        # Docker
        if ! command -v docker &> /dev/null; then
            curl -fsSL https://get.docker.com | sh
            systemctl enable docker && systemctl start docker
        fi

        # Node.js 24
        if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
            apt-get install -y nodejs
        fi

        # OpenClaw
        npm install -g openclaw

        mkdir -p /opt/factory
REMOTE_SETUP

    echo "[4/5] Copying factory files to remote server..."
    rsync -avz --exclude='.git' --exclude='node_modules' --exclude='.env' \
        -e "ssh -i $SSH_KEY_PATH" \
        "$SCRIPT_DIR/" "$SERVER_USER@$SERVER_IP:/opt/factory/"

    echo "[5/5] Generating .env and starting factory on remote..."
    # Generate .env locally, copy to remote
    generate_env_file "/tmp/factory-env-tmp"
    scp -i "$SSH_KEY_PATH" /tmp/factory-env-tmp/.env "$SERVER_USER@$SERVER_IP:/opt/factory/.env"
    rm -rf /tmp/factory-env-tmp

    # Update Caddyfile with actual domain
    ssh -i "$SSH_KEY_PATH" "$SERVER_USER@$SERVER_IP" \
        "sed -i 's/factory.yourdomain.com/$CLOUD_DOMAIN/g' /opt/factory/infrastructure/Caddyfile.cloud"

    # Start
    ssh -i "$SSH_KEY_PATH" "$SERVER_USER@$SERVER_IP" \
        "cd /opt/factory && docker compose -f infrastructure/docker-compose.cloud.yml up -d"

    echo ""
    echo "══════════════════════════════════════════════════"
    echo "  CLOUD SETUP COMPLETE"
    echo ""
    echo "  Provider:  $FACTORY_TARGET"
    echo "  Server IP: $SERVER_IP"
    echo "  Portal:    https://$CLOUD_DOMAIN"
    echo "  SSH:       ssh -i $SSH_KEY_PATH $SERVER_USER@$SERVER_IP"
    echo ""
    echo "  IMPORTANT: Point your DNS A record for"
    echo "  $CLOUD_DOMAIN → $SERVER_IP"
    echo "  Then wait 2-5 minutes for TLS certificate."
    echo ""
    echo "  Send your first idea to Telegram and watch it build."
    echo "══════════════════════════════════════════════════"
}

# ═══════════════════════════════════════════════════════════
# MAIN — Route to correct setup
# ═══════════════════════════════════════════════════════════

case "$FACTORY_TARGET" in
    local)
        setup_local
        ;;
    aws|azure|gcp|hetzner|digitalocean)
        # Check for required CLI tools
        case "$FACTORY_TARGET" in
            aws) command -v aws &>/dev/null || { echo "ERROR: Install AWS CLI first: pip install awscli"; exit 1; } ;;
            azure) command -v az &>/dev/null || { echo "ERROR: Install Azure CLI first: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"; exit 1; } ;;
            gcp) command -v gcloud &>/dev/null || { echo "ERROR: Install gcloud CLI first: https://cloud.google.com/sdk/docs/install"; exit 1; } ;;
        esac
        provision_cloud_vm "$FACTORY_TARGET"
        setup_remote_server
        ;;
    *)
        echo "ERROR: Unknown FACTORY_TARGET=$FACTORY_TARGET"
        echo "Valid options: local, aws, azure, gcp, hetzner, digitalocean"
        exit 1
        ;;
esac
